export enum DataImportActions {
  IMPORT_TRIGGERED = "IMPORT_TRIGGERED",
  DATA_REQUESTED = "DATA_REQUESTED",
  DATA_RECEIVED = "DATA_RECEIVED",
  DATA_PARSED = "DATA_PARSED",
  DATA_SAVED = "DATA_SAVED",
  IMPORT_COMPLETED = "IMPORT_COMPLETED",
}
